/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Asset, AuditSession, VarianceItem, TaggingTask } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'AST-2026-001',
    name: 'MacBook Pro 16" (M3 Max, 64GB)',
    category: 'Compute',
    status: 'Allocated',
    tagType: 'QR',
    tagStatus: 'Active',
    tagCode: 'QR-MBP-9812A',
    serialNumber: 'C02F9812L98A',
    cost: 3499,
    purchaseDate: '2026-01-15',
    custodian: 'Alex Rivera',
    department: 'Engineering',
    location: 'HQ Building A - Floor 4 (Desk 412)',
    lastAuditDate: '2026-04-10',
    notes: 'Primary developer workstation. Configured with external monitor profiles.',
  },
  {
    id: 'AST-2026-002',
    name: 'Latitude 7440 Intel Core i7',
    category: 'Compute',
    status: 'Allocated',
    tagType: 'Barcode',
    tagStatus: 'Active',
    tagCode: 'BAR-LAT-74403',
    serialNumber: 'DL744092X011',
    cost: 1450,
    purchaseDate: '2026-02-11',
    custodian: 'Sarah Jenkins',
    department: 'Finance',
    location: 'HQ Building A - Floor 2 (Office 203)',
    lastAuditDate: '2026-04-12',
    notes: 'Finance dashboard laptop. Access to corporate ERP locked to MAC address.',
  },
  {
    id: 'AST-2026-003',
    name: 'Cisco Catalyst 9300 48-Port Switch',
    category: 'Network',
    status: 'Allocated',
    tagType: 'RFID',
    tagStatus: 'Active',
    tagCode: 'RFID-CIS-93004',
    serialNumber: 'FOC2419X0B1',
    cost: 4800,
    purchaseDate: '2025-11-05',
    custodian: 'IT Network Ops',
    department: 'IT Infrastructure',
    location: 'HQ Server Room - Rack 03',
    lastAuditDate: '2026-03-20',
    notes: 'Core switch for physical networking. High availability configured.',
  },
  {
    id: 'AST-2026-004',
    name: 'iPad Pro 11" (M2, 256GB, Cellular)',
    category: 'Mobile',
    status: 'In Storage',
    tagType: 'QR',
    tagStatus: 'Commissioned',
    tagCode: 'QR-IPD-30421',
    serialNumber: 'DMP890A9F931',
    cost: 999,
    purchaseDate: '2026-03-01',
    custodian: 'Unassigned',
    department: 'Operations',
    location: 'HQ Building A - Floor 1 (IT Storage)',
    lastAuditDate: '2026-04-01',
    notes: 'Loaner device for field inspection workflows.',
  },
  {
    id: 'AST-2026-005',
    name: 'Herman Miller Aeron Chair (Graphite)',
    category: 'Furniture',
    status: 'Allocated',
    tagType: 'Barcode',
    tagStatus: 'Active',
    tagCode: 'BAR-AER-4892A',
    serialNumber: 'HM-AER-0921820',
    cost: 1250,
    purchaseDate: '2025-08-20',
    custodian: 'Marcus Sterling',
    department: 'Human Resources',
    location: 'HQ Building A - Floor 3 (Office 301)',
    lastAuditDate: '2026-04-22',
    notes: 'Aeron Size B standard graphite. Ergonomic customization applied.',
  },
  {
    id: 'AST-2026-006',
    name: 'Sony FE 70-200mm f/2.8 GM OSS II',
    category: 'Facility',
    status: 'In Storage',
    tagType: 'QR',
    tagStatus: 'Pending',
    tagCode: 'QR-SNY-70200',
    serialNumber: 'S-70200-GM201',
    cost: 2799,
    purchaseDate: '2026-05-10',
    custodian: 'Unassigned',
    department: 'Marketing',
    location: 'HQ Building A - Floor 1 (IT Storage)',
    lastAuditDate: undefined,
    notes: 'Newly received high-precision lens tool. Awaiting physical tagging verification.',
  },
  {
    id: 'AST-2026-007',
    name: 'Dell PowerEdge R760 Rack Server',
    category: 'Server',
    status: 'Allocated',
    tagType: 'RFID',
    tagStatus: 'Active',
    tagCode: 'RFID-DEL-R7603',
    serialNumber: 'DELL-R760-7A0B',
    cost: 12400,
    purchaseDate: '2025-12-15',
    custodian: 'IT Systems Team',
    department: 'IT Infrastructure',
    location: 'HQ Server Room - Rack 01',
    lastAuditDate: '2026-03-20',
    notes: 'Virtualization hypervisor server hosting internal engineering environments.',
  },
  {
    id: 'AST-2026-008',
    name: 'Fortinet FortiGate 100F Firewall',
    category: 'Network',
    status: 'Allocated',
    tagType: 'BLE',
    tagStatus: 'Active',
    tagCode: 'BLE-FT-100F92',
    serialNumber: 'FT100F-9812A93',
    cost: 3200,
    purchaseDate: '2026-02-18',
    custodian: 'IT Network Ops',
    department: 'IT Infrastructure',
    location: 'HQ Server Room - Rack 02',
    lastAuditDate: '2026-03-20',
    notes: 'Primary border security gateway device with live routing failovers.',
  },
  {
    id: 'AST-2026-009',
    name: 'Ergonomic Standing Desk (Oak, 160x80)',
    category: 'Furniture',
    status: 'Allocated',
    tagType: 'QR',
    tagStatus: 'Active',
    tagCode: 'QR-DSK-OK160',
    serialNumber: 'DK-OAK-98231',
    cost: 850,
    purchaseDate: '2025-09-01',
    custodian: 'Alex Rivera',
    department: 'Engineering',
    location: 'HQ Building A - Floor 4 (Desk 412)',
    lastAuditDate: '2026-04-10',
    notes: 'Dual motors standing table with integrated Cable Snake controller.',
  },
  {
    id: 'AST-2026-010',
    name: 'ThinkPad X1 Carbon Gen 11',
    category: 'Compute',
    status: 'Allocated',
    tagType: 'QR',
    tagStatus: 'Active',
    tagCode: 'QR-TPK-X1C11',
    serialNumber: 'TP-X1C11-98AL2',
    cost: 1899,
    purchaseDate: '2025-10-10',
    custodian: 'Helen Patel',
    department: 'Operations',
    location: 'HQ Building B - Floor 5 (Office 511)',
    lastAuditDate: '2026-04-15',
    notes: 'Executive operational laptop, preloaded with regional logistics portals.',
  }
];

export const INITIAL_AUDIT_SESSIONS: AuditSession[] = [
  {
    id: 'AUD-2026-001',
    title: 'Q2 Physical Audit - Server Rack Network Elements',
    targetLocation: 'HQ Server Room',
    status: 'In Progress',
    startDate: '2026-05-15',
    scannedCount: 2,
    totalCount: 3,
  },
  {
    id: 'AUD-2026-002',
    title: 'H1 Workspace Recon - Bldg A Floor 4 desks',
    targetLocation: 'HQ Building A - Floor 4',
    status: 'In Progress',
    startDate: '2026-05-20',
    scannedCount: 1,
    totalCount: 3,
  },
  {
    id: 'AUD-2026-003',
    title: 'Annual High-Value Asset Verification',
    targetLocation: 'All HQ Buildings',
    status: 'Planned',
    startDate: '2026-06-10',
    scannedCount: 0,
    totalCount: 10,
  }
];

export const INITIAL_VARIANCES: VarianceItem[] = [
  {
    id: 'VAR-2026-101',
    assetId: 'AST-2026-002',
    assetName: 'Latitude 7440 Intel Core i7',
    type: 'Location Mismatch',
    severity: 'Medium',
    bookValue: {
      location: 'HQ Building A - Floor 2 (Office 203)',
      custodian: 'Sarah Jenkins',
      status: 'Allocated'
    },
    scannedValue: {
      location: 'HQ Building A - Floor 4 (Desk 412)', // Scanned down dynamic dev level floor
      custodian: 'Sarah Jenkins',
      status: 'Allocated'
    },
    scannedAt: '2026-05-26T14:45:00Z',
    resolved: false,
    notes: 'Found laptop on Alex Rivera\'s desk on Floor 4, while the book lists Floor 2 Office 203. No physical transit or transfer request was signed.',
  },
  {
    id: 'VAR-2026-102',
    assetId: 'AST-2026-010',
    assetName: 'ThinkPad X1 Carbon Gen 11',
    type: 'Custodian Mismatch',
    severity: 'Low',
    bookValue: {
      location: 'HQ Building B - Floor 5 (Office 511)',
      custodian: 'Helen Patel',
      status: 'Allocated'
    },
    scannedValue: {
      location: 'HQ Building B - Floor 5 (Office 511)',
      custodian: 'Jessica Morris', // Scanned custodian different
      status: 'Allocated'
    },
    scannedAt: '2026-05-27T09:12:00Z',
    resolved: false,
    notes: 'Desk check verified computer operates in Office 511, but the current daily user is Jessica Morris (Operations Trainee). Need custodial reassignment.',
  },
  {
    id: 'VAR-2026-103',
    assetId: 'AST-2026-005',
    assetName: 'Herman Miller Aeron Chair (Graphite)',
    type: 'Missing Asset',
    severity: 'High',
    bookValue: {
      location: 'HQ Building A - Floor 3 (Office 301)',
      custodian: 'Marcus Sterling',
      status: 'Allocated'
    },
    scannedValue: {
      location: 'Not Found',
      custodian: 'Unknown',
      status: 'Missing'
    },
    scannedAt: '2026-05-27T11:30:00Z',
    resolved: false,
    notes: 'Office 301 is completely empty; employee Marcus Sterling reported working remotely fulltime now. The Aeron chair is missing from office site.',
  }
];

export const INITIAL_TAGGING_TASKS: TaggingTask[] = [
  {
    id: 'TSK-2026-501',
    assetId: 'AST-2026-006',
    assetName: 'Sony FE 70-200mm f/2.8 GM OSS II',
    category: 'Facility',
    requestedAt: '2026-05-25',
    priority: 'Urgent',
    status: 'Pending',
  },
  {
    id: 'TSK-2026-502',
    assetId: 'AST-2026-004',
    assetName: 'iPad Pro 11" (M2, 256GB, Cellular)',
    category: 'Mobile',
    requestedAt: '2026-05-26',
    priority: 'Routine',
    status: 'Sticker Printed',
  }
];
